/* ────────────────────────────────────────────────────────────────
   TEMPLATE — copy this file to  config.js  and paste in your real URLs.
   config.js is git-ignored, so your URLs never enter the repo/history.

     cp config.example.js config.js   (or just copy/rename in Explorer)

   In production, config.js is generated by the GitHub Pages deploy
   workflow from repo Secrets (SUBMIT_URL / OPTIONS_URL) — see
   .github/workflows/deploy-pages.yml.
   ──────────────────────────────────────────────────────────────── */
window.RSM_CONFIG = {
  // Flow A — "When an HTTP request is received" (POST). Receives the form JSON.
  SUBMIT_URL: "",

  // Flow B — "When an HTTP request is received" (GET). Returns dropdown options.
  // Optional — leave blank to use the form's built-in DEFAULT_OPTIONS.
  OPTIONS_URL: ""
};
